server:
  port: 6002
spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://127.0.0.1:3360/SchoolDB
    username: root
    password: root
  application:
    name: FEE-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://myimage:8761/eureka/
  instance:
    hostname: myimage